export const phases = [
  { id: "foundation", number: "I", title: "启动与基础", level: "Beginner" },
  { id: "reliable", number: "II", title: "可靠交互", level: "Beginner → Intermediate" },
  { id: "extensions", number: "III", title: "扩展与自动化", level: "Intermediate" },
  { id: "production", number: "IV", title: "工程化与进阶", level: "Advanced" },
];

export const courseMetadata = {
  hermesVersion: "v0.20.5",
  hermesReleaseTag: "v2026.8.19",
  verifiedOn: "2026-08-24",
  releaseUrl: "https://github.com/NousResearch/hermes-agent/releases/tag/v2026.8.19",
};

const assetBaseUrl = import.meta.env?.BASE_URL || "/";

const option = (id, label, detail) => ({ id, label, detail });

export const onboardingTracks = [
  {
    id: "desktop",
    label: "桌面应用",
    title: "下载 Hermes Desktop",
    summary: "适合第一次使用 Hermes 的学习者。安装器会配置桌面应用与 CLI，两者共享配置、会话和 Skills。",
    recommended: true,
    steps: [
      { title: "打开官方下载页", body: "在 macOS 或 Windows 下载对应的 Hermes Desktop 安装器。", action: "打开下载页", url: "https://hermes-agent.nousresearch.com/" },
      { title: "运行安装器", body: "按向导完成依赖与 Hermes 核心安装；Windows 无需管理员权限。" },
      { title: "完成首次设置", body: "选择 Provider 和模型，先完成一次普通聊天，再启用外部平台。", command: "hermes setup" },
      { title: "已有 CLI 时启动桌面端", body: "桌面端会复用现有配置、密钥、会话与 Skills。", command: "hermes desktop" },
    ],
    verify: "桌面端能创建新会话、选择模型并收到一条普通回复。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/desktop",
  },
  {
    id: "mac",
    label: "macOS 终端",
    title: "在 macOS 安装 Hermes CLI",
    summary: "只需预先安装 Git；官方安装器会管理 uv、Python 3.11、Node.js 22、ripgrep 与 ffmpeg。",
    steps: [
      { title: "检查 Git", body: "如果命令不可用，先安装 Xcode Command Line Tools。", command: "git --version" },
      { title: "运行官方安装器", body: "在 Terminal 中执行一行安装命令。", command: "curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash" },
      { title: "刷新终端环境", body: "新开终端，或在当前 zsh 会话重新加载 PATH。", command: "source ~/.zshrc" },
      { title: "配置并验收", body: "完成 Setup 后先运行 Doctor，再开始普通聊天。", command: "hermes setup && hermes doctor && hermes" },
    ],
    verify: "hermes doctor 无阻断错误，hermes 能进入聊天界面。",
    docs: "https://hermes-agent.nousresearch.com/docs/getting-started/installation",
  },
  {
    id: "windows",
    label: "Windows 原生",
    title: "在 Windows 原生安装 Hermes",
    summary: "适合希望直接在 PowerShell、Windows Terminal 或桌面应用中运行 Hermes 的用户。",
    steps: [
      { title: "打开 PowerShell", body: "使用普通用户权限即可，无需以管理员身份运行。" },
      { title: "运行官方安装脚本", body: "安装位置默认为 %LOCALAPPDATA%\\hermes，并写入用户 PATH。", command: "iex (irm https://hermes-agent.nousresearch.com/install.ps1)" },
      { title: "重新打开终端", body: "安装结束后新开 PowerShell，让用户 PATH 生效。" },
      { title: "检查并启动", body: "完成配置检查；需要 GUI 时从同一安装启动桌面端。", command: "hermes doctor\nhermes desktop" },
    ],
    verify: "新终端能识别 hermes，桌面端与 CLI 能看到同一套会话。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/windows-native",
  },
  {
    id: "wsl",
    label: "Windows WSL2",
    title: "通过 WSL2 使用 Linux 版 Hermes",
    summary: "适合偏好 Linux 工具链、systemd 和本地开发环境的 Windows 用户；官方建议 Ubuntu LTS。",
    steps: [
      { title: "安装 WSL2", body: "在管理员 PowerShell 执行并按提示重启。", command: "wsl --install" },
      { title: "确认使用 WSL2", body: "目标发行版的 VERSION 应为 2，而不是 1。", command: "wsl --list --verbose" },
      { title: "在 Ubuntu 内安装", body: "打开 WSL2 终端后使用 Linux/macOS 安装器。", command: "curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash" },
      { title: "刷新并运行", body: "项目建议放在 ~/code，而不是 /mnt/c，以减少跨文件系统开销。", command: "source ~/.bashrc && hermes" },
    ],
    verify: "WSL 发行版显示 VERSION 2，Hermes 能在 Linux 文件系统中的项目目录正常聊天。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/windows-wsl-quickstart",
  },
  {
    id: "feishu",
    label: "连接飞书",
    title: "把 Hermes 接入飞书群聊和私聊",
    summary: "推荐使用 WebSocket 长连接：Hermes 主动向飞书建立连接，不需要公网 URL。",
    steps: [
      { title: "启动接入向导", body: "选择 Feishu / Lark。推荐用飞书手机扫描二维码自动创建应用并保存凭据。", command: "hermes gateway setup" },
      { title: "手动模式准备应用", body: "在飞书开放平台创建企业自建应用，启用机器人，保存 App ID 与 App Secret。", action: "打开飞书应用控制台", url: "https://open.feishu.cn/app" },
      { title: "配置权限和事件", body: "至少添加 im:message、im:message:send_as_bot、im:resource、im:chat、im:chat:readonly，并订阅 im.message.receive_v1。" },
      { title: "发布并启动 Gateway", body: "发布应用版本并等待管理员审批；然后启动 Gateway，在群聊中 @机器人做冒烟测试。", command: "hermes gateway" },
    ],
    verify: "群聊中 @Hermes 后能收到回复；生产环境已配置 FEISHU_ALLOWED_USERS。",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/feishu",
  },
];

export const surfaceGuides = {
  desktop: {
    label: "Hermes Desktop",
    title: "从课程界面切换到真实 Desktop",
    summary: "先认识真实窗口中的稳定地标，再在同一个 Agent 运行时里完成新会话、模型确认、消息发送与工具审批。",
    image: `${assetBaseUrl}ui-reference/hermes-desktop-official.png`,
    imageAlt: "NousResearch 官方 Hermes Desktop 界面，左侧为导航和会话，中间为聊天区，底部为输入框与状态栏",
    sourceLabel: "官方仓库界面实景",
    sourceUrl: "https://github.com/NousResearch/hermes-agent/blob/main/apps/desktop/pr-assets/session-source-folders.png",
    sourceNote: "界面来自 NousResearch/hermes-agent 官方仓库；具体文案和位置可能随 Desktop 更新变化。",
    hotspots: [
      { id: "new", number: "1", label: "New session", detail: "左上角创建会话；创建后会话会出现在左侧 Sessions 列表。", x: 4, y: 6 },
      { id: "tools", number: "2", label: "Skills & Tools", detail: "进入能力管理；真实任务前确认只启用所需工具。", x: 8, y: 10.5 },
      { id: "messaging", number: "3", label: "Messaging", detail: "进入消息平台管理；飞书接入状态与 Gateway 配置从这里查看。", x: 12, y: 15 },
      { id: "composer", number: "4", label: "消息输入框", detail: "底部 Composer 用于发任务、拖入附件和查看排队消息。", x: 49, y: 94 },
      { id: "status", number: "5", label: "连接与模型状态", detail: "底部状态栏确认 Gateway ready、当前模型与上下文状态。", x: 79, y: 98 },
    ],
    steps: [
      { title: "启动并确认连接", body: "运行 hermes desktop。等待窗口底部出现可用连接状态，不要在启动遮罩仍存在时发送任务。" },
      { title: "创建独立会话", body: "点击左上角 New session；确认新会话出现在 Sessions 中，避免把练习混入生产会话。" },
      { title: "先做无工具回执", body: "在 Composer 发送校验 Prompt。先证明模型与会话工作，再练习 File 或 Terminal。" },
      { title: "审查一次工具请求", body: "发送只读任务，核对工具、目标路径和范围；首次审批选择 Allow Once / 仅允许一次。" },
    ],
    verificationPrompt: "请只回复 DESKTOP_OK，不要调用任何工具。",
    expected: "DESKTOP_OK",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/desktop",
  },
  feishu: {
    label: "飞书端",
    title: "从开发者控制台走到真实群聊",
    summary: "配置侧负责让事件和卡片可达，飞书客户端负责 @提及、审批与接收结果；两条路径都通过才算接入完成。",
    sourceLabel: "官方飞书接入文档",
    sourceUrl: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/feishu",
    sourceNote: "飞书菜单名称可能因企业版本略有差异；事件名、权限 Scope 和 Hermes 行为以官方文档为准。",
    routes: [
      {
        title: "开发者控制台",
        steps: ["应用列表 → 凭证与基础信息", "权限管理 → 导入必需 Scope", "事件与回调 → WebSocket 长连接", "订阅 im.message.receive_v1 与 card.action.trigger", "应用功能 → 机器人 → 启用交互式卡片", "版本管理 → 创建并发布版本"],
      },
      {
        title: "飞书客户端",
        steps: ["进入机器人私聊或已添加机器人的群聊", "群聊输入 @Hermes，确认提及变为蓝色实体", "发送校验 Prompt，观察 Typing 表情", "危险命令出现审批卡时先核对工具与范围", "首次操作选择允许一次，并检查最终结果"],
      },
    ],
    steps: [
      { title: "先验证私聊", body: "私聊会响应每一条消息，适合先排除 @提及门和群组策略带来的变量。" },
      { title: "再验证群聊提及", body: "群聊默认只有显式 @Hermes 才触发；普通文本没有回复是预期行为。" },
      { title: "观察处理状态", body: "Agent 工作时会在消息上显示 Typing 表情，完成后清除；失败时可能显示 CrossMark。" },
      { title: "验证原生审批卡", body: "卡片按钮报 200340 时，检查 card.action.trigger、交互式卡片能力与应用版本是否已发布。" },
    ],
    verificationPrompt: "@Hermes 请只回复 FEISHU_OK，不要调用任何工具。",
    expected: "FEISHU_OK",
    docs: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/feishu",
  },
};

export const lessons = [
  {
    id: "installation-channels", number: "00", phaseId: "foundation", level: "Beginner", title: "下载与多端接入", shortTitle: "安装 Hermes，并完成桌面与飞书首轮体验",
    summary: "根据设备选择桌面安装器或终端安装，完成首次配置，再把同一个 Hermes 安全地连接到飞书。",
    objective: "能够选择正确安装路径，完成 Doctor 验收，并解释桌面端与飞书端如何共享 Hermes 运行时。",
    prerequisites: ["macOS 或 Windows 设备", "可访问官方安装页", "一个模型 Provider"],
    preQuiz: { prompt: "第一次接触 Hermes，官方推荐哪种安装路径？", options: [option("desktop", "Hermes Desktop 安装器", "同时安装桌面应用与 CLI"), option("source", "直接从源码构建", "更适合贡献者"), option("docker", "先搭建生产容器", "不适合作为首次体验")], correct: "desktop", explanation: "macOS/Windows 首次使用推荐桌面安装器；熟悉终端后也可以选择 CLI-only 安装。" },
    command: "hermes gateway setup",
    trace: ["选择设备与安装方式", "完成 Setup 和 Doctor", "在桌面端执行一次任务", "连接飞书并验证 @提及"],
    steps: [
      { title: "先选安装入口", body: "macOS/Windows 初学者优先使用 Desktop 安装器；CLI 用户选择 macOS shell、Windows 原生 PowerShell 或 WSL2。" },
      { title: "先验收再扩展", body: "安装后运行 Setup、Doctor 和一次普通聊天。只有基础会话通过后，才继续配置桌面工作流或飞书 Gateway。" },
      { title: "桌面端共享运行时", body: "hermes desktop 会复用当前配置、密钥、Sessions 与 Skills。桌面端是操作界面，不是另一套独立 Agent。" },
      { title: "飞书走 Gateway", body: "推荐 WebSocket 长连接，不需要公网地址。群聊默认要求 @机器人；生产使用必须限制用户和群组范围。" },
    ],
    checkpoints: ["选择安装路径", "识别真实界面地标", "完成本机检测或回执", "验证飞书审批链路"],
    lab: { task: "完成一个从安装到飞书消息的端到端冒烟测试。", input: "一台 macOS/Windows 设备、可用 Provider、飞书企业自建应用或扫码创建权限。", procedure: ["选择并执行对应安装路径", "运行 Setup、Doctor 和一次普通聊天", "对照官方实景图，在 Desktop 新建独立会话并完成 DESKTOP_OK 回执", "运行 gateway setup 并选择 Feishu/Lark", "发布飞书应用并在群聊 @Hermes 完成 FEISHU_OK 回执", "触发一次测试审批卡并选择仅允许一次"], successCriteria: ["CLI 与桌面端共享会话", "能定位 Desktop 的会话、消息、工具与连接状态", "Doctor 无阻断错误", "飞书只响应允许用户和有效 @提及", "审批卡可点击且没有 200340", "App Secret 未出现在聊天或截图中"], evidence: "保存脱敏的 Doctor 结论、DESKTOP_OK、FEISHU_OK 和审批卡成功状态；截图必须遮盖 App ID、Secret 与用户标识。", recovery: "先停止 Gateway，再撤销测试群权限或下线应用版本；Desktop/CLI 仍应能完成普通聊天。" },
    practice: { type: "choice", prompt: "Hermes 运行在个人电脑且没有公网 URL，连接飞书应该优先选择什么？", options: [option("websocket", "WebSocket 长连接", "出站连接，无需公网入口"), option("webhook", "公开 Webhook", "需要可达 HTTP 地址"), option("poll", "每分钟轮询", "不是官方推荐连接方式")], correct: "websocket", success: "正确。个人电脑或私有服务器优先使用 WebSocket 长连接。", hint: "选择不要求公网 URL、由 Hermes 主动建立的连接方式。" },
    takeaways: ["先通过界面地标建立真实操作路径", "桌面和飞书共享同一个 Hermes 运行时"], troubleshooting: "命令不可用时先刷新 PATH；飞书不回复时检查应用发布、im.message.receive_v1、Gateway、@提及和白名单；审批卡报 200340 时检查 card.action.trigger 与交互式卡片能力。",
    references: [{ label: "Installation", url: "https://hermes-agent.nousresearch.com/docs/getting-started/installation" }, { label: "Desktop", url: "https://hermes-agent.nousresearch.com/docs/user-guide/desktop" }, { label: "Windows Native", url: "https://hermes-agent.nousresearch.com/docs/user-guide/windows-native" }, { label: "Feishu", url: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/feishu" }],
  },
  {
    id: "setup-doctor", number: "01", phaseId: "foundation", level: "Beginner", title: "环境与诊断", shortTitle: "先建立一个可工作的 Hermes",
    summary: "从安装、Setup 到 Doctor，建立可重复的最小启动路径；先通过一次聊天验收，再逐步添加能力。",
    objective: "完成最小配置，读懂诊断结果，并按正确顺序恢复一个无法对话的 Hermes。",
    prerequisites: ["Python 3.11+", "可访问模型 Provider", "终端基础操作"],
    preQuiz: { prompt: "安装后第一条验收标准应该是什么？", options: [option("chat", "完成一次普通聊天", "证明 Provider、模型和基础运行时可用"), option("cron", "先创建 Cron", "自动化依赖更长的链路"), option("mcp", "先接入 MCP", "会引入额外变量")], correct: "chat", explanation: "先得到一个可工作的聊天基线，后续故障才容易定位。" },
    command: "hermes doctor",
    trace: ["运行 hermes setup", "选择 Quick / Full / Blank Slate", "完成首次聊天", "用 doctor 复核环境"],
    steps: [
      { title: "选择安装模式", body: "Quick Setup 适合首次使用；Full Setup 展开所有选项；Blank Slate 仅保留 Provider、模型、File 与 Terminal，适合从最小能力面开始。" },
      { title: "先验收基础聊天", body: "运行 hermes --tui 并完成一个无需工具的问答。不要在这个基线通过前接入 Gateway、Cron、Skills、MCP 或路由。" },
      { title: "读懂 Doctor", body: "hermes doctor 用于检查配置、凭据和关键依赖。诊断的价值是缩小故障域，而不是把所有配置重新安装一遍。" },
      { title: "按层恢复", body: "建议顺序是 doctor → model → setup → sessions → gateway。每一步只验证一个层级，避免同时改变多个变量。" },
    ],
    checkpoints: ["选择合适 Setup 模式", "完成首次聊天", "运行 Doctor", "按层恢复故障"],
    lab: { task: "为一台新设备制定最小验收流程。", input: "Hermes 已安装，但尚未配置 Provider，也没有启用任何扩展。", procedure: ["运行 hermes setup 并选择 Quick Setup", "配置 Provider 与模型", "进入 TUI 完成一次普通问答", "运行 hermes doctor 记录检查结果"], successCriteria: ["聊天有正常模型响应", "Doctor 无阻断性错误", "未提前启用 Gateway/MCP"], evidence: "记录 Hermes 版本、Provider/模型名称、基础聊天回执和 Doctor 的通过/阻断项，不记录密钥。", recovery: "基础聊天失败时按 doctor → model → setup 顺序恢复，每次只改一个变量。" },
    practice: { type: "multi", prompt: "选择合理的首次安装验收顺序。", options: [option("setup", "hermes setup", "生成基础配置"), option("chat", "首次聊天", "验证 Provider 与模型"), option("doctor", "hermes doctor", "检查环境健康"), option("gateway", "Gateway setup", "暂不需要"), option("cron", "Cron create", "暂不需要")], correct: ["setup", "chat", "doctor"], success: "路径正确：先配置、再对话、最后复核健康状态。", hint: "只选择建立最小工作基线所需的三步。" },
    takeaways: ["先让一个聊天回合工作", "一次只改变一个故障变量"], troubleshooting: "若 Doctor 通过但聊天失败，先用 hermes model 检查 Provider、模型名称与凭据，再回到 setup。",
    references: [{ label: "Quickstart", url: "https://hermes-agent.nousresearch.com/docs/getting-started/quickstart" }, { label: "Configuration", url: "https://hermes-agent.nousresearch.com/docs/user-guide/configuration" }],
  },
  {
    id: "agent-loop", number: "02", phaseId: "foundation", level: "Beginner", title: "Agent Loop", shortTitle: "从任务到可观察行动",
    summary: "理解意图、计划、工具调用、观察结果与继续迭代组成的 Agent 回合，并为副作用设置审批。",
    objective: "识别一次完整 Agent 回合，为读写动作选择匹配风险的授权范围。",
    prerequisites: ["完成 Lesson 01", "能够进入 Hermes TUI"],
    preQuiz: { prompt: "Hermes 和普通聊天模型最关键的区别是什么？", options: [option("tools", "能在循环中调用工具", "行动结果会返回模型继续判断"), option("long", "回答更长", "长度不是 Agent 的定义"), option("persona", "有固定人格", "SOUL 只是其中一层")], correct: "tools", explanation: "Agent 的核心是可观察、可迭代的工具调用闭环。" },
    command: "hermes --tui",
    trace: ["理解任务与上下文", "选择最小工具", "审批副作用", "观察结果并验证"],
    steps: [
      { title: "模型负责决策", body: "模型根据任务和观察结果决定下一步；运行时负责注册工具、执行、权限、会话和结果回传。" },
      { title: "轨迹比答案重要", body: "TUI 把工具进度、审批与最终回答分开呈现。检查它实际做了什么，而不只看最后一句话。" },
      { title: "授权匹配风险", body: "读取通常风险较低；写文件、执行命令、发消息会产生副作用。首次运行应优先单次、窄范围授权。" },
      { title: "用证据结束回合", body: "命令退出码为零不代表任务正确。要求 Hermes 汇报变更、测试、未覆盖项与恢复方式。" },
    ],
    checkpoints: ["识别 Agent Loop", "选择最小工具", "设置审批范围", "要求验证证据"],
    lab: { task: "让 Hermes 盘点一个 Markdown 目录并生成只读报告。", input: "一个包含 5 个 Markdown 文件的练习目录。", procedure: ["先要求列出文件和计划", "只批准读取与搜索", "审查报告中的文件计数", "需要写摘要时单独批准一次写入"], successCriteria: ["初次分析没有写入", "报告与目录实际文件数一致", "写入授权只覆盖目标摘要"], evidence: "对照实际目录记录文件计数、工具调用列表和唯一写入目标；用 Git diff 或文件哈希证明其他文件未改变。", recovery: "若发生越界写入，立即停止回合，撤销目标变更并把允许路径、工具和停止条件写回 Prompt。" },
    practice: { type: "choice", prompt: "Hermes 要在当前目录写入摘要，且这是第一次运行。如何授权？", options: [option("once", "仅允许这一次", "完成后自动失效"), option("session", "本会话始终允许", "后续同类写入不再询问"), option("always", "永久允许", "未来会话也跳过确认"), option("deny", "拒绝全部", "任务停在只读阶段")], correct: "once", success: "正确。首次写入使用单次授权，兼顾效率与最小权限。", hint: "选择能完成任务的最小授权。" },
    takeaways: ["Agent 是循环而非单次生成", "副作用需要可观察和可恢复"], troubleshooting: "若工具循环反复执行同一步，暂停并补充成功标准、允许的工具和最大尝试次数。",
    references: [{ label: "CLI", url: "https://hermes-agent.nousresearch.com/docs/user-guide/cli" }, { label: "Tools", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/tools" }],
  },
  {
    id: "models-profiles", number: "03", phaseId: "foundation", level: "Beginner", title: "模型切换与故障回退", shortTitle: "切换主模型，并保留可工作的回退路径",
    summary: "在模型选择器中建立可用基线、切换主模型并做同题对比；连接失败时按单变量顺序恢复。",
    objective: "完成一次模型切换和回切，能用响应、延迟与工具调用结果判断模型是否适合当前任务。",
    prerequisites: ["理解基础配置目录", "至少有一个可用 Provider"],
    preQuiz: { prompt: "切换候选模型后所有请求都超时，第一步应该做什么？", options: [option("rollback", "回切已知可用模型", "先恢复工作基线"), option("everything", "同时重配 Provider、Skills 和 Gateway", "会扩大故障域"), option("retry", "无限重复原请求", "不会定位连接或权限问题")], correct: "rollback", explanation: "先回切已知可用模型恢复基线，再用 Doctor 和单变量检查定位问题。" },
    command: "hermes model",
    trace: ["记录当前可用模型", "用固定任务建立基线", "切换候选模型复测", "失败时回切并运行 Doctor"],
    steps: [
      { title: "先保存已知可用基线", body: "运行 hermes model，记录当前 Provider 与模型 ID；发送固定的无工具 Prompt，保存响应是否成功和大致延迟。" },
      { title: "一次只换一个模型", body: "在同一 Profile、同一会话边界下切换候选模型，再运行完全相同的 Prompt。不要同时改密钥、Skills 或 Gateway。" },
      { title: "用真实任务比较", body: "至少测试普通问答、结构化输出和一次只读工具调用。模型能聊天不代表工具选择和 JSON 输出都可靠。" },
      { title: "失败就回到基线", body: "候选模型超时、无权限或工具调用异常时，先回切已知可用模型，再运行 hermes doctor；需要刷新模型列表时使用 hermes model --refresh。" },
    ],
    checkpoints: ["记录可用基线", "同题切换对比", "验证工具调用", "完成故障回切"],
    lab: { task: "完成一次主模型 A/B 切换与恢复演练。", input: "一个已知可用模型、一个候选模型，以及固定的问答/JSON/只读工具三条测试。", procedure: ["记录当前 Provider 与模型 ID", "运行三条测试并保存基线", "用 hermes model 切换候选模型后原样复测", "模拟候选不可用并回切基线", "运行 hermes doctor 确认恢复"], successCriteria: ["两轮使用相同测试输入", "记录响应、延迟和工具结果", "候选失败后可恢复聊天", "实验记录不含 API 密钥"], evidence: "保留两轮相同输入、模型 ID、响应是否合格、工具调用结果和回切后的 MODEL_BASELINE_OK。", recovery: "回切实验前记录的 Provider 与模型，运行 Doctor，再重跑同一条无工具基线 Prompt。" },
    practice: { type: "builder", prompt: "为研究任务规划一次可恢复的模型切换。", fields: [{ id: "provider", label: "候选模型来源", type: "select", options: ["Nous Portal", "OpenRouter", "本地端点"] }, { id: "profile", label: "测试 Profile", type: "select", options: ["research", "default", "personal"] }], expected: { profile: "research" }, commandTemplate: ({ provider, profile }) => `hermes -p ${profile || "<profile>"} model  # 切换到 ${provider || "<provider>"} 后运行固定测试并保留回退模型`, success: "切换在隔离 Profile 中完成，并保留了明确回退路径。", hint: "使用 research Profile，避免候选模型影响日常入口。" },
    takeaways: ["模型切换必须同题验证", "先回切基线再继续排错"], troubleshooting: "模型列表陈旧时运行 hermes model --refresh；切换后失败时先回切已知可用模型，再依次检查 doctor、Provider 凭据、模型权限和网络。",
    references: [{ label: "Configuring Models", url: "https://hermes-agent.nousresearch.com/docs/user-guide/configuring-models" }, { label: "Hermes 4.3 model card", url: "https://huggingface.co/NousResearch/Hermes-4.3-36B" }],
  },
  {
    id: "prompt-contracts", number: "04", phaseId: "reliable", level: "Beginner", title: "Prompt 契约", shortTitle: "把需求写成可验收的契约",
    summary: "用目标、上下文、边界、输出结构和成功标准构造稳定 Prompt，并练习 JSON Schema 结构化输出。",
    objective: "把模糊请求改写成可验证 Prompt，并判断何时使用 reasoning 与结构化输出。",
    prerequisites: ["理解 Agent Loop", "能够描述任务输入与输出"],
    preQuiz: { prompt: "哪个字段最能减少“看起来完成但无法验收”？", options: [option("criteria", "成功标准", "明确完成证据"), option("tone", "语气", "只影响表达"), option("length", "字数", "不是正确性的充分条件")], correct: "criteria", explanation: "成功标准把主观完成转化为可检查证据。" },
    command: "hermes chat --prompt '<task contract>'",
    trace: ["声明目标与输入", "限定工具和边界", "定义输出 Schema", "按成功标准自检"],
    steps: [
      { title: "五段式任务契约", body: "写清目标、已知上下文、允许范围、输出格式和成功标准。先约束事实与边界，再调整语气。" },
      { title: "结构化输出", body: "对下游程序使用 JSON Schema，明确 required 字段、枚举和禁止额外字段；不要靠解析自然语言猜测状态。" },
      { title: "选择推理模式", body: "复杂规划与约束冲突适合 reasoning；简单抽取和格式转换可用 non-reasoning，以降低延迟与无关展开。" },
      { title: "把失败变成输入", body: "把验证错误、缺失字段和工具输出反馈给下一轮，并限制修复范围。不要只重复原 Prompt。" },
    ],
    checkpoints: ["写出任务目标", "限定作用域", "定义输出结构", "列出成功标准"],
    lab: { task: "设计一个仓库健康报告 Prompt。", input: "仓库路径、允许的只读工具、期望 JSON 字段。", procedure: ["列出目标和非目标", "定义 findings/risks/tests 字段", "要求引用文件路径", "用一条缺字段样例测试修复回合"], successCriteria: ["输出可通过 JSON 校验", "每条发现包含证据", "未请求写入或联网"], evidence: "保存最终 Prompt、Schema 校验通过结果，以及故意缺字段时返回的 validation_errors。", recovery: "输出失控时恢复上一个可用 Prompt，缩小 Schema，并一次只增加一个字段或约束。" },
    practice: { type: "multi", prompt: "选择一个可靠任务契约必须包含的四项。", options: [option("goal", "明确目标", "说明最终要得到什么"), option("context", "输入与上下文", "提供必要事实"), option("boundary", "工具与边界", "限制副作用"), option("criteria", "成功标准", "定义验收证据"), option("flattery", "礼貌夸赞", "不影响可验证性")], correct: ["goal", "context", "boundary", "criteria"], success: "任务契约完整，Hermes 可以据此执行并自检。", hint: "选择能约束目标、输入、执行和验收的内容。" },
    takeaways: ["Prompt 是任务契约", "结构化输出服务于下游验证"], troubleshooting: "JSON 经常不合法时，缩小 Schema、给一个合法示例，并要求失败时只返回 validation_errors。",
    references: [{ label: "Hermes 4.3 structured outputs", url: "https://huggingface.co/NousResearch/Hermes-4.3-36B" }, { label: "CLI", url: "https://hermes-agent.nousresearch.com/docs/user-guide/cli" }],
  },
  {
    id: "tools-context", number: "05", phaseId: "reliable", level: "Intermediate", title: "工具、Context 与审批", shortTitle: "组合最小且可审计的工具链",
    summary: "从任务反推 Toolset，使用 Context Files 固化项目约定，并让高风险操作经过明确审批。",
    objective: "为代码库任务选择最小工具集，区分上下文指令与长期记忆，并设置写入门。",
    prerequisites: ["能够写任务契约", "理解本地文件副作用"],
    preQuiz: { prompt: "项目编码规范最适合放在哪一层？", options: [option("context", "项目 Context File", "随项目版本控制并按目录生效"), option("memory", "全局 Memory", "可能污染其他项目"), option("prompt", "每次手写", "容易遗漏")], correct: "context", explanation: "稳定项目约定应进入项目上下文文件并随代码审查。" },
    command: "hermes tools",
    trace: ["读取项目 Context", "启用最小 Toolset", "先只读形成计划", "写入前请求审批"],
    steps: [
      { title: "工具越少越清晰", body: "每增加一种工具都会增加选择成本与攻击面。先从 File 和 Terminal 的只读用法开始，再按任务增加 Browser 或代码执行。" },
      { title: "Context Files 管项目规则", body: "把目录结构、构建命令和代码规范作为版本化上下文；不要把 API 密钥、临时任务或个人隐私写进去。" },
      { title: "读写分阶段", body: "先只读盘点并输出计划，再开放目标文件的写入。审批应说明工具、路径、次数和预期变化。" },
      { title: "验证工具结果", body: "要求引用读取过的文件、实际命令和退出状态，并用测试或 diff 证明结果符合任务契约。" },
    ],
    checkpoints: ["读取 Context", "限制 Toolset", "分离读写阶段", "验证工具证据"],
    lab: { task: "扫描仓库并生成 README 草稿。", input: "一个已有源码但无 README 的练习仓库。", procedure: ["读取项目 Context", "用 File/Terminal 只读搜索", "输出 README 结构计划", "仅批准写入 README.draft.md"], successCriteria: ["未启用无关 Browser/Image 工具", "草稿引用真实脚本", "没有覆盖已有文件"], evidence: "记录启用的 Toolset、实际读取路径、README.draft.md 和 Git diff，证明原始文件未被覆盖。", recovery: "删除草稿或恢复 Checkpoint，并把无关工具关闭；重新执行前先让 Hermes 复述 Context 边界。" },
    practice: { type: "multi", prompt: "选择完成“扫描当前仓库并生成 README 草稿”的最小能力集合。", options: [option("terminal", "Terminal", "列目录并搜索"), option("file", "File", "读取并写草稿"), option("approval", "Write approval", "写入前暂停"), option("browser", "Browser", "控制网页"), option("image", "Image generation", "生成视觉资产")], correct: ["terminal", "file", "approval"], success: "工具链足够完成任务，写入仍处于你的控制。", hint: "任务不需要访问网页或生成图片。" },
    takeaways: ["项目规则进入 Context", "工具按任务最小化"], troubleshooting: "若 Agent 忽略 Context，检查文件位置与作用域，并在 Prompt 中要求先复述适用规则再执行。",
    references: [{ label: "Tools", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/tools" }, { label: "Context Files", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/context-files" }],
  },
  {
    id: "sessions-memory", number: "06", phaseId: "reliable", level: "Intermediate", title: "Session、Memory 与 SOUL", shortTitle: "让上下文分层而不过度记忆",
    summary: "区分原始会话、压缩经验、稳定用户信息、人格原则与 Profile 隔离，设计可审查的记忆写入。",
    objective: "把不同信息放入正确层级，并通过 Memory gate 避免短期或敏感信息长期化。",
    prerequisites: ["使用过至少两个 Session", "了解 Profile"],
    preQuiz: { prompt: "要找回上周调试的完整报错，应先查哪里？", options: [option("session", "Session search", "保留原始交互与工具上下文"), option("memory", "Agent Memory", "是压缩后的经验"), option("soul", "SOUL.md", "只描述原则")], correct: "session", explanation: "原始历史用会话搜索，复用结论才进入 Memory。" },
    command: "hermes sessions list",
    trace: ["搜索原始 Session", "提取可复用结论", "审查长期价值与敏感性", "经 Memory gate 写入"],
    steps: [
      { title: "Session 保存事实", body: "Session 是原始交互记录，适合找回命令、报错和当时上下文；不要把全部历史塞回当前 Prompt。" },
      { title: "Memory 保存经验", body: "Memory 适合可复用流程、项目约定和失败结论；临时状态、一次性需求和秘密不应长期保存。" },
      { title: "SOUL 定原则", body: "SOUL.md 描述长期行为风格与价值边界，不是知识库、配置文件或任务清单。" },
      { title: "写入要可审查", body: "长期记忆会改变后续行为。启用审批并记录来源、适用范围、更新时间和删除条件。" },
    ],
    checkpoints: ["检索 Session", "提炼 Memory", "区分 SOUL", "审批长期写入"],
    lab: { task: "整理一次失败调试并决定哪些内容长期保存。", input: "完整报错、三条尝试命令、最终根因和个人访问令牌。", procedure: ["用 Session 保留原始记录", "提炼根因与通用修复", "排除令牌和临时路径", "批准一条带来源的 Memory"], successCriteria: ["Memory 不含秘密", "保留可复用根因", "能够从 Session 找回原始证据"], evidence: "保存 Session 搜索命中、脱敏后的 Memory 文本和敏感字段排除清单。", recovery: "发现错误或敏感 Memory 时立即删除或修订，并在新会话验证旧结论不再被召回。" },
    practice: { type: "choice", prompt: "“某依赖在 Node 22 下失败，固定到 Node 20 可恢复”最适合保存在哪里？", options: [option("memory", "项目 Agent Memory", "可复用的项目经验"), option("soul", "SOUL.md", "人格原则"), option("user", "User profile", "个人稳定偏好"), option("none", "完全不保存", "会丢失复用价值")], correct: "memory", success: "正确。这是可复用的项目排错经验。", hint: "它不是人格或个人身份事实。" },
    takeaways: ["Session 是记录，Memory 是提炼", "长期写入必须可审查"], troubleshooting: "发现错误 Memory 时立即删除或修订，并在当前会话显式声明不再使用旧结论。",
    references: [{ label: "Sessions", url: "https://hermes-agent.nousresearch.com/docs/user-guide/sessions" }, { label: "Memory", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/memory" }, { label: "Profiles", url: "https://hermes-agent.nousresearch.com/docs/user-guide/profiles" }],
  },
  {
    id: "skills-plugins-mcp", number: "07", phaseId: "extensions", level: "Intermediate", title: "Skills 安装与冒烟测试", shortTitle: "从搜索、审查到触发和卸载",
    summary: "用真实 CLI 流程搜索、预览、安装并触发一个 Skill；失败时能定位依赖、权限或触发描述。",
    objective: "在隔离 Profile 中完成一项 Skill 的安装、只读验证、更新检查与卸载恢复。",
    prerequisites: ["理解 Toolset", "能够审查配置和来源"],
    preQuiz: { prompt: "安装陌生 Skill 前最先应该执行什么？", options: [option("inspect", "先 inspect 内容与来源", "安装前看到说明和风险"), option("force", "直接 --force 安装", "会绕过拦截结论"), option("prod", "直接在生产 Profile 测试", "扩大影响范围")], correct: "inspect", explanation: "先预览来源、依赖和动作，再决定是否安装。" },
    command: "hermes skills browse",
    trace: ["search 找候选", "inspect 审查内容", "install 到隔离 Profile", "触发、检查并卸载"],
    steps: [
      { title: "先搜索再锁定标识", body: "运行 hermes skills search <关键词>，记录候选的完整 identifier、来源和版本；不要只凭名称相似安装。" },
      { title: "安装前预览", body: "运行 hermes skills inspect <identifier>，检查触发描述、依赖、外部命令、写入路径和网络目标。扫描被阻断时不要使用 --force 掩盖原因。" },
      { title: "隔离安装并确认可见", body: "使用 hermes -p research skills install <identifier>，随后运行 skills list。先用只读任务触发，观察是否真的加载了目标 Skill。" },
      { title: "验收更新与恢复", body: "运行 skills check/audit 检查更新和风险；不符合预期时用 skills uninstall <name> 移除，并在新会话复测基线。" },
    ],
    checkpoints: ["锁定完整 identifier", "完成安装前审查", "只读触发成功", "会检查和卸载"],
    lab: { task: "安装并验收一个真实 Skill。", input: "Skills Hub 候选项、research Profile 与一个无副作用测试任务。", procedure: ["search 并记录完整 identifier", "inspect 审查来源、依赖和动作", "安装到 research Profile 并运行 list", "开启新会话发送能明确触发该 Skill 的只读任务", "运行 check/audit 后卸载并复测普通聊天"], successCriteria: ["来源与 identifier 可追溯", "未使用 --force 绕过拦截", "响应中有可检查的触发证据", "卸载后基础聊天仍工作"], evidence: "记录 identifier、inspect 摘要、list/check/audit 结果和只读冒烟任务的触发证据。", recovery: "卸载目标 Skill、开启新会话并复测普通聊天；若依赖残留，按 inspect 中的安装范围清理。" },
    practice: { type: "multi", prompt: "选择陌生 Skill 的正确安装验收顺序。", options: [option("search", "search 候选", "锁定完整 identifier"), option("inspect", "inspect 内容", "检查来源、依赖与副作用"), option("install", "隔离 Profile 安装", "限制影响范围"), option("smoke", "只读冒烟测试", "证明能触发且输出正确"), option("force", "遇到拦截直接 --force", "跳过风险原因")], correct: ["search", "inspect", "install", "smoke"], success: "顺序正确：发现、审查、隔离安装、再用无副作用任务验收。", hint: "选择四个保留审查和恢复路径的步骤。" },
    takeaways: ["安装前 inspect，安装后实测触发", "任何扩展都要有卸载路径"], troubleshooting: "Skill 未触发时先开新会话并让请求明确匹配描述；依赖失败时检查 inspect 输出；异常时 uninstall 后复测，不要先用 --force。",
    references: [{ label: "Skills", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/skills" }, { label: "Hermes CLI source", url: "https://github.com/NousResearch/hermes-agent/tree/main/hermes_cli/subcommands" }],
  },
  {
    id: "automation", number: "08", phaseId: "extensions", level: "Intermediate", title: "Gateway、Cron、Hooks 与 Batch", shortTitle: "把一次成功变成可靠自动化",
    summary: "区分消息入口、定时触发、事件钩子和批处理，设计可追踪、可重试、有交付证据的自动化。",
    objective: "从触发、任务、工作目录到交付目标构建一个可观测的工作日早报。",
    prerequisites: ["基础聊天稳定", "已理解 Skills 与审批"],
    preQuiz: { prompt: "定时触发成功是否等于结果送达？", options: [option("no", "不等于", "执行与 Delivery 是不同状态"), option("yes", "等于", "忽略了运行或发送失败")], correct: "no", explanation: "自动化至少要区分调度、执行、验证和交付状态。" },
    command: "hermes gateway status",
    trace: ["Gateway 接收或保持连接", "Cron/Hook/Batch 触发", "Agent 执行并验证", "结果路由并记录状态"],
    steps: [
      { title: "选择正确触发器", body: "Gateway 是消息入口，Cron 处理时间计划，Hook 响应事件，Batch 处理成组输入。飞书可从 Desktop 的 Messaging 页面观察连接，再回到群聊用 @提及验证真实入口。" },
      { title: "自动化任务要自包含", body: "保存 schedule/trigger、prompt、Profile、工作目录、Skills、超时和 delivery，避免依赖某次交互里的隐含上下文。" },
      { title: "保留幂等性", body: "任务重试不能重复发消息或覆盖数据。为输出加入日期/任务 ID，并在写入前检查是否已经完成。" },
      { title: "交付必须可追踪", body: "记录触发、运行、验证、发送四种状态和失败原因，给人工提供重跑与停用路径。" },
    ],
    checkpoints: ["选择触发机制", "任务自包含", "设计幂等性", "追踪交付状态"],
    lab: { task: "创建工作日项目早报。", input: "工作日 09:00、项目目录、状态汇总 Prompt、Telegram 目标。", procedure: ["先在普通聊天中跑通 Prompt", "创建 Cron 并固定 Profile/目录", "配置 Telegram delivery", "模拟失败并查看历史"], successCriteria: ["同一天重跑不重复发送", "失败记录可查询", "停用和手动重跑路径明确"], evidence: "保存 Cron 定义、一次成功运行、一次失败历史和幂等键；消息目标只记录脱敏别名。", recovery: "先停用 Cron，再确认 Gateway 状态和最近运行记录；清除重复任务后才允许手动重跑。" },
    practice: { type: "builder", prompt: "构建工作日 09:00 的项目早报，并发送到 Telegram。", fields: [{ id: "schedule", label: "Schedule", type: "select", options: ["weekdays at 09:00", "every 5m", "daily at 23:00"] }, { id: "delivery", label: "Delivery", type: "select", options: ["Telegram", "CLI only", "Discord"] }, { id: "task", label: "Task", type: "text", placeholder: "汇总状态、阻塞项和今日计划" }], expected: { schedule: "weekdays at 09:00", delivery: "Telegram" }, commandTemplate: ({ schedule, delivery, task }) => `hermes cron create "${schedule || "<schedule>"}" "${task || "<task>"}"  # ${delivery || "<target>"}`, success: "自动化具备明确时间、任务和交付目标。", hint: "题目指定工作日 09:00 与 Telegram，Task 也不能为空。" },
    takeaways: ["触发、执行、交付是不同状态", "先手动跑通再自动化"], troubleshooting: "任务未送达时先查 gateway status 与 Cron 历史，区分未触发、执行失败和 delivery 失败。",
    references: [{ label: "Cron", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/cron" }, { label: "Batch Processing", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/batch-processing" }, { label: "Hooks", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/hooks" }, { label: "Feishu", url: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/feishu" }],
  },
  {
    id: "delegation-routing", number: "09", phaseId: "extensions", level: "Intermediate", title: "并行任务与结果收口", shortTitle: "在真实会话里启动、观察并验收子任务",
    summary: "把互不依赖的只读工作拆成子任务，在 Desktop/TUI 观察运行状态，并由主会话统一核对证据。",
    objective: "完成一次三路并行检查，能从 /agents 发现卡住任务，并在最终报告中处理冲突与缺失。",
    prerequisites: ["理解 Profile 隔离", "能够写成功标准"],
    preQuiz: { prompt: "什么任务最适合并行委派？", options: [option("independent", "输入和写入相互独立", "可以并行后统一汇总"), option("samefile", "同时改同一文件", "冲突风险高"), option("unknown", "目标仍然模糊", "子任务无法自包含")], correct: "independent", explanation: "并行的前提是依赖和写入边界清楚。" },
    command: "/agents",
    trace: ["准备三份自包含任务单", "从主会话发起委派", "用 /agents 观察状态", "汇总后运行集成验证"],
    steps: [
      { title: "先写三张任务单", body: "每张都写清输入文件、只读边界、返回字段和停止条件。两个任务需要改同一文件时不要并行。" },
      { title: "从主会话明确发起", body: "要求 Hermes 将三张任务单分别委派并在全部返回后汇总；先让子任务只产出证据，不直接修改共享文件。" },
      { title: "打开 /agents 看运行态", body: "在 TUI 或消息入口使用 /agents 查看活动子任务。记录 running/completed/failed；卡住时检查其最近工具动作，而不是重复启动相同任务。" },
      { title: "主会话做最终验收", body: "把子任务结论与文件、命令输出或链接逐条对应；冲突时回查证据。只有主会话通过集成检查后才算完成。" },
    ],
    checkpoints: ["写出独立任务单", "启动三路委派", "读懂 /agents", "完成集中验收"],
    lab: { task: "在 Desktop 或 TUI 完成一次发布前并行检查。", input: "依赖清单、现有测试输出、文档链接，以及统一的 findings/command/evidence/status 返回格式。", procedure: ["分别写依赖、测试、链接三张只读任务单", "要求主 Agent 并行委派", "运行 /agents 并记录每个子任务状态", "等待结果后要求主 Agent 标注冲突和缺失", "亲自运行一条集成验证命令"], successCriteria: ["没有子任务写共享文件", "每项结论都含证据", "/agents 中没有遗留 running 任务", "最终报告包含集成验证结果"], evidence: "保存三张任务单、/agents 最终状态、逐项证据和主会话运行的集成验证命令。", recovery: "停止遗留运行项；出现冲突时回到原始路径、命令和版本复核，不用多数结果代替验收。" },
    practice: { type: "multi", prompt: "选择可并行委派的三条独立工作流。", options: [option("research", "依赖安全公告", "只读外部研究"), option("tests", "测试失败归类", "分析既有输出"), option("docs", "文档链接核对", "检查链接与示例"), option("samea", "修改 App.jsx 上半段", "写共享文件"), option("sameb", "修改 App.jsx 下半段", "写同一文件")], correct: ["research", "tests", "docs"], success: "拆分合理：输入和写入边界独立，可并行后统一汇总。", hint: "避免两个子任务同时写同一个文件。" },
    takeaways: ["并行前先消除共享写入", "/agents 用于观察，主会话负责验收"], troubleshooting: "子任务长期 running 时查看最近工具动作并停止重复工作；结果冲突时回到路径、命令和版本证据，不做多数表决。",
    references: [{ label: "Delegation", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/delegation" }, { label: "Hermes Agent", url: "https://github.com/NousResearch/hermes-agent" }],
  },
  {
    id: "sandbox-security", number: "10", phaseId: "production", level: "Advanced", title: "Sandbox、Egress 与 ACP", shortTitle: "把代码执行放进明确边界",
    summary: "比较 local、Docker 与 SSH 后端，使用 Egress Proxy 限制网络，并通过 ACP 把 Hermes 接入编辑器协议。",
    objective: "为不可信仓库选择隔离后端、网络策略和恢复点，并验证边界确实生效。",
    prerequisites: ["理解工具审批", "具备 Docker 或 SSH 基础"],
    preQuiz: { prompt: "运行陌生仓库安装脚本时，首选哪种后端？", options: [option("docker", "Docker Sandbox", "隔离文件系统和进程"), option("local", "Local", "直接影响主机"), option("gateway", "Gateway", "不是执行隔离后端")], correct: "docker", explanation: "Docker 是陌生代码的合理起点，仍需额外限制挂载和网络。" },
    command: "hermes config set terminal.backend docker",
    trace: ["选择执行后端", "限制挂载与凭据", "启用 Egress 策略", "验证阻断与恢复"],
    steps: [
      { title: "后端按信任选择", body: "local 适合受信环境；docker 提供本机隔离；ssh 用于受控远端。Modal、Daytona、Vercel Sandbox 等适合弹性工作负载。" },
      { title: "隔离不只是一条命令", body: "限制挂载目录、用户权限、环境变量、资源和生命周期。不要把主机凭据或 Docker socket 默认映射进去。" },
      { title: "网络默认收紧", body: "使用 Egress Proxy 控制允许访问的域名和协议，并测试被禁止请求确实失败。网络白名单应服务于明确任务。" },
      { title: "ACP 是集成边界", body: "hermes acp 让兼容客户端通过 Agent Client Protocol 连接 Hermes；仍应保持 Profile、工具和审批策略一致。" },
    ],
    checkpoints: ["选择 Sandbox", "限制挂载与秘密", "验证 Egress", "理解 ACP 边界"],
    lab: { task: "在隔离环境审查陌生 Node 仓库。", input: "只读源码、允许 npm registry、禁止其他外网。", procedure: ["切换 terminal.backend=docker", "只挂载练习目录", "配置并启动 Egress", "运行依赖审计并测试禁止域名"], successCriteria: ["主机目录未暴露", "仅 npm registry 可访问", "退出后容器状态可清理"], evidence: "记录挂载清单、允许域名成功请求、禁止域名失败请求和容器清理结果。", recovery: "停止并删除练习容器，恢复原 Terminal backend，撤销临时 Egress 规则后再检查主机目录。" },
    practice: { type: "multi", prompt: "选择运行陌生代码前必须具备的四项控制。", options: [option("backend", "隔离执行后端", "Docker 或受控 SSH"), option("mount", "最小目录挂载", "只暴露任务输入"), option("egress", "网络白名单", "限制外连"), option("secret", "不注入无关凭据", "降低泄漏风险"), option("root", "永久 root 权限", "扩大破坏面")], correct: ["backend", "mount", "egress", "secret"], success: "隔离边界完整：执行、文件、网络和秘密都已收紧。", hint: "选择减少陌生代码权限的四项。" },
    takeaways: ["Sandbox 与 Egress 是两条边界", "隔离必须通过负向测试验证"], troubleshooting: "Docker 后端失败时检查 daemon、镜像和挂载；Egress 误拦截时只添加所需域名，不要临时全开放。",
    references: [{ label: "Security", url: "https://hermes-agent.nousresearch.com/docs/user-guide/security" }, { label: "Docker", url: "https://hermes-agent.nousresearch.com/docs/user-guide/docker" }, { label: "ACP", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/acp" }],
  },
  {
    id: "backup-restore", number: "11", phaseId: "production", level: "Advanced", title: "备份、更新与迁移恢复", shortTitle: "在升级或换机前留下可验证恢复点",
    summary: "创建完整备份和快速快照，验证归档可读性，并在隔离环境演练更新或换机后的恢复顺序。",
    objective: "在不暴露凭据的前提下生成备份、验证归档，并写出可执行的导入与恢复验收清单。",
    prerequisites: ["至少完成一个 Profile 配置", "有可用的临时备份目录"],
    preQuiz: { prompt: "运行 hermes update 前最可靠的准备是什么？", options: [option("backup", "先创建并验证备份", "保留配置、会话和可恢复状态"), option("screenshot", "只截一张设置页", "无法恢复状态"), option("memory", "只复制 MEMORY.md", "遗漏其他关键数据")], correct: "backup", explanation: "升级前先生成可验证的恢复点，再记录当前版本与基础验收结果。" },
    command: "hermes backup",
    trace: ["记录版本与基线", "创建完整备份/快速快照", "验证归档可读取", "隔离导入并重跑验收"],
    steps: [
      { title: "先记录恢复基线", body: "保存 Hermes 版本、Profile 名称、当前模型和 doctor 结果；不要把 Token、App Secret 或聊天内容写入共享实验报告。" },
      { title: "创建两类恢复点", body: "hermes backup 生成完整 zip，适合换机；hermes backup --quick 生成快速快照，适合更新前短期回退。备份文件本身包含敏感状态，应加密保存。" },
      { title: "备份后立即验证", body: "确认命令成功、文件非空；macOS/Linux 用 unzip -t <backup.zip>，Windows PowerShell 用 tar -tf <backup.zip> 检查归档。只看到文件名不等于已验证恢复。" },
      { title: "恢复必须隔离演练", body: "hermes import <backup.zip> 会覆盖现有文件，只能在干净测试环境或明确确认后运行；恢复后依次检查 doctor、模型、会话、Skills 和 Gateway。" },
    ],
    checkpoints: ["记录版本基线", "生成完整备份", "验证 zip 完整", "写出恢复验收顺序"],
    lab: { task: "完成一次升级前备份和恢复桌面演练。", input: "当前 Hermes 环境、一个仅当前用户可读的备份目录，以及可丢弃的测试环境。", procedure: ["记录版本、Profile 与 doctor 结果", "运行 hermes backup 并记录输出文件", "运行 unzip -t 验证归档", "在可丢弃环境执行 hermes import <backup.zip>", "按 doctor → model → sessions → skills → gateway 顺序验收"], successCriteria: ["备份文件存在且归档测试通过", "备份未上传到 Git 或公开网盘", "恢复环境可完成普通聊天", "Gateway 和自动化由人工确认后再启用"], evidence: "记录版本、备份文件名与校验结果，以及恢复后的 Doctor、模型、会话、Skills、Gateway 五层状态。", recovery: "导入前保留目标环境第二份备份并停止 Gateway；失败时放弃测试环境，不覆盖原工作环境。" },
    practice: { type: "choice", prompt: "完整备份创建成功后，下一步应该做什么？", options: [option("verify", "验证 zip 并记录恢复命令", "尽早发现损坏或错误路径"), option("delete", "立即删除旧环境", "尚未证明可恢复"), option("publish", "上传到公开仓库", "可能泄露敏感状态"), option("assume", "只看命令退出码", "缺少归档完整性证据")], correct: "verify", success: "正确。先验证归档并保留恢复清单，再考虑更新或迁移。", hint: "备份完成不等于恢复路径已经成立。" },
    takeaways: ["备份必须同时验证", "导入操作只在隔离环境演练"], troubleshooting: "备份很慢时确认输出不在 ~/.hermes 内且磁盘空间充足；导入前停止相关 Gateway，并保留当前环境的第二份备份。",
    references: [{ label: "Hermes Agent repository", url: "https://github.com/NousResearch/hermes-agent" }, { label: "Checkpoints", url: "https://hermes-agent.nousresearch.com/docs/user-guide/checkpoints-and-rollback" }],
  },
  {
    id: "capstone", number: "12", phaseId: "production", level: "Advanced", title: "评测驱动毕业项目", shortTitle: "把 Hermes 工作流交付到生产边界",
    summary: "综合 Prompt、Tools、Memory、Automation、Delegation、Sandbox 与评测，设计一个可审计、可恢复的 PR 审查助手。",
    objective: "交付一个有基线、评测集、权限边界、失败策略与运行证据的完整工作流设计。",
    prerequisites: ["完成前三阶段", "掌握基本 Git 与测试"],
    preQuiz: { prompt: "生产化前最先需要哪项证据？", options: [option("baseline", "可重复评测基线", "知道当前表现与退化"), option("demo", "一次成功演示", "不能代表稳定性"), option("autonomy", "永久跳过审批", "扩大风险")], correct: "baseline", explanation: "没有基线就无法判断改动是否真正提升可靠性。" },
    command: "hermes checkpoints list",
    trace: ["限定仓库与分支", "运行离线评测", "审批后执行", "保留 Checkpoint 与报告"],
    steps: [
      { title: "先定义风险预算", body: "明确可读仓库、允许分支、可写文件、外部消息目标、人工审批点和不可接受失败。" },
      { title: "建立评测集", body: "覆盖正常、边界、恶意 Prompt、工具失败和恢复场景；记录正确率、误报、成本、延迟与人工接管率。" },
      { title: "设计失败策略", body: "超时、Provider 故障、测试失败或权限不足时应停止、降级或请求人工，不得静默跳过。" },
      { title: "用证据完成交付", body: "最终报告包含配置版本、实际变更、评测结果、Checkpoint、回滚步骤和仍需人工判断的风险。" },
    ],
    checkpoints: ["限定作用域", "建立评测基线", "验证失败策略", "提供回滚证据"],
    lab: { task: "设计并评审一个定时 PR 审查 Agent。", input: "只读代码、可写审查草稿、Slack 交付、30 条测试任务。", procedure: ["定义权限矩阵", "建立基线并记录指标", "在 Sandbox 运行失败注入", "审批后发送一条测试交付", "生成运行手册与回滚说明"], successCriteria: ["高风险动作需审批", "评测覆盖失败路径", "每次运行有 Checkpoint/日志", "报告暴露剩余风险"], evidence: "提交权限矩阵、30 条评测结果、失败注入记录、Checkpoint 标识、一次审批交付和剩余风险清单。", recovery: "停止调度与消息交付，回滚到已验证 Checkpoint，并用失败样例确认退化已消失。" },
    practice: { type: "multi", prompt: "上线 PR 审查 Agent 前必须具备哪些控制？", options: [option("scope", "仓库与分支白名单", "限制目标"), option("approval", "写入与发送审批", "控制副作用"), option("rollback", "Checkpoint / Git 恢复点", "支持恢复"), option("evaluation", "测试集与运行证据", "证明表现"), option("yolo", "永久跳过确认", "提高风险")], correct: ["scope", "approval", "rollback", "evaluation"], success: "毕业挑战完成：能力已经进入可审查、可恢复、可度量的运行边界。", hint: "选择作用域、审批、恢复和评测四类控制。" },
    takeaways: ["生产化以评测和风险预算为起点", "自动化必须保留人工接管"], troubleshooting: "指标退化时先回滚配置/Skill/模型版本，再复现失败样例；不要在生产任务上直接试错。",
    references: [{ label: "Checkpoints", url: "https://hermes-agent.nousresearch.com/docs/user-guide/checkpoints-and-rollback" }, { label: "Learning Path", url: "https://hermes-agent.nousresearch.com/docs/getting-started/learning-path" }, { label: "Self Evolution", url: "https://github.com/NousResearch/hermes-agent-self-evolution" }],
  },
];

export const repositories = [
  { name: "NousResearch/hermes-agent", role: "官方核心", language: "Python + TypeScript", url: "https://github.com/NousResearch/hermes-agent", idea: "把模型、工具运行时、持久记忆、Skills、消息网关与自动化组合成可扩展 Agent harness。", design: "Provider 可替换、界面与核心解耦、能力按需披露、会话与长期记忆分层、副作用显式治理。", features: ["TUI / CLI / Desktop", "Memory / Sessions", "Skills / MCP / Plugins", "Cron / Gateway / Delegation"] },
  { name: "microsoft/AI-For-Beginners", role: "教学体系参考", language: "Markdown + Jupyter", url: "https://github.com/microsoft/AI-For-Beginners", idea: "用环境准备、课前测验、理论、可执行实验、课后测验与延伸阅读形成低门槛学习闭环。", design: "按周递进、项目驱动、频繁低风险反馈，每个实验明确任务、输入、执行步骤和期望结果。", features: ["课程 Setup", "Pre/Post Quiz", "Notebook / Code Challenge", "Assignment / Self-study"] },
  { name: "NousResearch/Hermes-4.3-36B", role: "官方模型资料", language: "Transformers", url: "https://huggingface.co/NousResearch/Hermes-4.3-36B", idea: "36B 混合推理模型，面向工具调用、结构化输出、长上下文和通用对话。", design: "Reasoning 与 non-reasoning 模式并存，使用 Chat Template 和显式工具调用标记适配多种 Serving。", features: ["Function calling", "JSON Schema", "Hybrid reasoning", "vLLM / SGLang / GGUF"] },
  { name: "NousResearch/hermes-agent-self-evolution", role: "官方实验项目", language: "Python", url: "https://github.com/NousResearch/hermes-agent-self-evolution", idea: "用 DSPy + GEPA 对 Skills、提示与代码进行基于评测的迭代优化。", design: "把自我改进变成候选生成、评测、比较与保留优胜版本的闭环。", features: ["GEPA 优化", "Skill 演化", "可度量评测", "实验追踪"] },
  { name: "NousResearch/atropos", role: "官方 RL 工具链", language: "Python", url: "https://github.com/NousResearch/atropos", idea: "为 Agent 和语言模型训练构建可复现的强化学习环境与 rollout 工作流。", design: "用显式环境、奖励与评测把行为优化建立在可测任务上。", features: ["RL environments", "Rollouts", "Reward design", "Training workflows"] },
  { name: "fathah/hermes-desktop", role: "社区桌面端", language: "TypeScript", url: "https://github.com/fathah/hermes-desktop", idea: "用原生桌面工作台降低安装、Provider 配置和日常管理门槛。", design: "围绕会话、Profile、Memory、Skills、Schedules 与 Gateway 组织 GUI。", features: ["引导式安装", "流式工具进度", "Profile / Memory", "Schedules / Messaging"] },
  { name: "outsourc-e/hermes-workspace", role: "社区 Web 工作台", language: "JavaScript + React", url: "https://github.com/outsourc-e/hermes-workspace", idea: "把仅聊天的 Portable 模式与 Gateway 增强模式明确分级，并在能力缺失时显示可恢复状态。", design: "默认 loopback、能力门控、健康检查和可见降级，避免后端不可用时出现空白界面。", features: ["Portable / Enhanced", "Capability gates", "Health checks", "Loopback defaults"] },
  { name: "microsoft/ai-agents-for-beginners", role: "Agent 教学参考", language: "Jupyter + Markdown", url: "https://github.com/microsoft/ai-agents-for-beginners", idea: "按目标组织多条 Agent 学习路径，并用可重复 smoke tests 验证状态、关键词和多轮结果。", design: "每课统一目标、Try this、自检与继续学习，课程目录和 Study Guide 提供多路径入口。", features: ["Study Guide", "Goal-based paths", "JSON smoke tests", "Multi-turn checks"] },
  { name: "huggingface/agents-course", role: "实战评测参考", language: "MDX + Python", url: "https://github.com/huggingface/agents-course", idea: "用阶段课程、最终项目、结构化提交和自动评分把学习结果变成可验证 artifact。", design: "基础单元逐步进入框架、RAG 和综合任务，开放式 Agent 结果通过明确任务与评测反馈收口。", features: ["Hands-on units", "Final assignment", "Evaluation API", "Benchmark"] },
  { name: "0xNyk/awesome-hermes-agent", role: "社区资源索引", language: "Markdown", url: "https://github.com/0xNyk/awesome-hermes-agent", idea: "聚合 Surfaces、Skills、Plugins、Memory Providers 与 Guides。", design: "通过类别和成熟度帮助学习者发现生态，同时保留来源审查责任。", features: ["Skills", "Plugins", "Memory providers", "Guides"] },
  { name: "alchaincyf/hermes-agent-orange-book", role: "中文学习资料", language: "PDF / Markdown", url: "https://github.com/alchaincyf/hermes-agent-orange-book", idea: "从自改进、记忆、工具、多 Agent、安全与部署建立中文整体视角。", design: "概念解释配合界面和架构分析，补充官方文档之外的学习路径。", features: ["中文指南", "记忆分析", "多 Agent", "安全边界"] },
];

export const learningResources = [
  { id: "official-docs", title: "Hermes Agent 官方文档", kind: "在线文档", language: "英文", authority: "官方", access: "全文公开", url: "https://hermes-agent.nousresearch.com/docs/", summary: "安装、Desktop、CLI、Provider、Tools、Skills、Memory、Cron、Messaging、安全和排错的事实基准。", lessonIds: lessons.map((lesson) => lesson.id) },
  { id: "official-repo", title: "NousResearch/hermes-agent", kind: "源码与 README", language: "英文 / 中文", authority: "官方", access: "全文公开", url: "https://github.com/NousResearch/hermes-agent", summary: "用于核对当前安装命令、CLI、Gateway、迁移行为、Release 与实现边界。", lessonIds: ["installation-channels", "setup-doctor", "agent-loop", "skills-plugins-mcp", "delegation-routing", "backup-restore", "capstone"] },
  { id: "orange-book", title: "Hermes Agent 橙皮书 2.0", kind: "PDF 电子书", language: "中文", authority: "社区", access: "在线预览 / 下载", url: "https://github.com/alchaincyf/hermes-agent-orange-book/blob/main/Hermes-Agent%E6%A9%99%E7%9A%AE%E4%B9%A62.0-v260607.pdf", summary: "用中文串联 Desktop、浏览器管理、记忆、Skills、多 Agent、消息平台与安全；具体命令需回查官方资料。", lessonIds: ["installation-channels", "sessions-memory", "skills-plugins-mcp", "automation", "delegation-routing", "sandbox-security"] },
  { id: "awesome", title: "awesome-hermes-agent", kind: "资源目录", language: "英文", authority: "社区", access: "全文公开", url: "https://github.com/0xNyk/awesome-hermes-agent", summary: "按 Surfaces、Skills、Plugins、Memory Providers、Tools 与 Guides 寻找进阶材料。", lessonIds: ["skills-plugins-mcp", "automation", "delegation-routing", "capstone"] },
  { id: "zh-course", title: "hermes-agent-zh", kind: "GitHub 教程", language: "中文", authority: "社区", access: "全文公开", url: "https://github.com/dongsheng123132/hermes-agent-zh", summary: "覆盖 macOS、Windows、云端部署、Provider、Ollama、Cron、MCP、IM 接入、案例与 FAQ。", lessonIds: ["installation-channels", "setup-doctor", "models-profiles", "skills-plugins-mcp", "automation", "backup-restore"] },
  { id: "papaya-video", title: "Hermes Agent 保姆级教学", kind: "YouTube 视频", language: "中文", authority: "社区", access: "YouTube 直接观看", url: "https://www.youtube.com/watch?v=-EivK7vpOXY", summary: "演示本机/云端安装、Telegram、Memory、OpenRouter、搜索、Subagent、Cron、Skills、Notion、备份与防火墙。", lessonIds: ["installation-channels", "sessions-memory", "skills-plugins-mcp", "automation", "delegation-routing", "backup-restore"] },
  { id: "tips-video", title: "Hermes Agent 新手使用十大技巧", kind: "YouTube 视频", language: "中文", authority: "社区", access: "YouTube 直接观看", url: "https://www.youtube.com/watch?v=hLiN_X7dzdw", summary: "公开章节元数据覆盖模型、SOUL、Memory、聊天通道、Doctor、UI、迁移与 Skills。", lessonIds: ["setup-doctor", "models-profiles", "sessions-memory", "skills-plugins-mcp", "backup-restore"] },
  { id: "desktop-video", title: "Hermes Agent 桌面版正式发布", kind: "YouTube 视频", language: "中文", authority: "社区", access: "YouTube 直接观看", url: "https://www.youtube.com/watch?v=FdSVeOAd480", summary: "适合观察 Windows、macOS、Linux 桌面版的真实界面与首次操作。", lessonIds: ["installation-channels"] },
];

export const architectureLayers = [
  { title: "Curriculum", detail: "13 课、4 阶段与 3 条目标路线；每课包含诊断、核心操作、真实实验、证据、恢复、课后检查与来源。" },
  { title: "Learning Engine", detail: "路线推荐、搜索、Prompt 契约、脱敏证据评分、恢复演练与双证据掌握度由可测试的纯函数驱动。" },
  { title: "Persistence", detail: "localStorage v4 默认保存；登录后可选 Supabase GitHub/邮箱同步，并兼容迁移 v1-v3 数据。" },
  { title: "Safety Shell", detail: "模拟、loopback Companion 与证据导入三层能力明确分开；不执行 Prompt，不上传原始证据，不读取凭据或消息。" },
];
